# Generated by Django 2.2 on 2021-07-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='time',
            field=models.CharField(max_length=60),
        ),
    ]
