# Generated by Django 2.2 on 2021-07-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike_app', '0002_auto_20210713_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
