# Generated by Django 2.2 on 2021-07-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike_app', '0003_hike_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='pets',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
