# Generated by Django 2.2 on 2021-07-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike_app', '0004_auto_20210717_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='pets',
            field=models.CharField(max_length=10),
        ),
    ]
