# Generated by Django 2.2 on 2021-07-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike_app', '0005_auto_20210718_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
